--FACTURACOMPRA, DETALLECOMPRA, PROVEEDOR
CREATE TRIGGER eliminar_detalles_al_borrar_factura
BEFORE DELETE ON FACTURACOMPRA
FOR EACH ROW
BEGIN
    DELETE FROM DETALLECOMPRA
    WHERE IDCOMPRA = OLD.IDCOMPRA;
END;

CREATE TRIGGER eliminar_facturas_al_borrar_proveedor
BEFORE DELETE ON PROVEEDOR
FOR EACH ROW
BEGIN
    DELETE FROM FACTURACOMPRA
    WHERE IDPROVEEDOR = OLD.IDPROVEEDOR;
END;

CREATE TRIGGER trigger_sumar_existencia_despues_insert
AFTER INSERT ON DETALLECOMPRA
BEGIN
  UPDATE DETALLEEXISTENCIA
  SET CANTIDADEXISTENCIA = CANTIDADEXISTENCIA + NEW.CANTIDADCOMPRA
  WHERE IDARTICULO = NEW.IDARTICULO
    AND IDFARMACIA = (
      SELECT IDFARMACIA FROM FACTURACOMPRA WHERE IDCOMPRA = NEW.IDCOMPRA
    );
END;

CREATE TRIGGER trigger_actualizar_existencia_despues_update
AFTER UPDATE OF CANTIDADCOMPRA ON DETALLECOMPRA
BEGIN
  UPDATE DETALLEEXISTENCIA
  SET CANTIDADEXISTENCIA = CANTIDADEXISTENCIA + (NEW.CANTIDADCOMPRA - OLD.CANTIDADCOMPRA)
  WHERE IDARTICULO = NEW.IDARTICULO
    AND IDFARMACIA = (
      SELECT IDFARMACIA FROM FACTURACOMPRA WHERE IDCOMPRA = NEW.IDCOMPRA
    );
END;
--FIN

CREATE TRIGGER eliminar_articulo_al_borrar_forma_farmaceutica
BEFORE DELETE ON FORMAFARMACEUTICA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDFORMAFARMACEUTICA = OLD.IDFORMAFARMACEUTICA;
END;

CREATE TRIGGER eliminar_articulo_al_borrar_marca
BEFORE DELETE ON MARCA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDMARCA = OLD.IDMARCA;
END;

CREATE TRIGGER eliminar_articulo_al_borrar_viaadministracion
BEFORE DELETE ON VIAADMINISTRACION
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDVIAADMINISTRACION = OLD.IDVIAADMINISTRACION;
END;

CREATE TRIGGER eliminar_receta_al_borrar_doctor
AFTER DELETE ON DOCTOR
FOR EACH ROW
BEGIN
    DELETE FROM RECETA
    WHERE IDDOCTOR = OLD.IDDOCTOR;
END;

CREATE TRIGGER eliminar_detalles_venta_al_borrar_factura_venta
BEFORE DELETE ON FACTURAVENTA
FOR EACH ROW
BEGIN
    DELETE FROM DETALLEVENTA
    WHERE IDVENTA = OLD.IDVENTA;
END;

CREATE TRIGGER eliminar_subcategorias_al_borrar_categoria
BEFORE DELETE ON CATEGORIA
FOR EACH ROW
BEGIN
    DELETE FROM SUBCATEGORIA
    WHERE IDCATEGORIA = OLD.IDCATEGORIA;
END;

CREATE TRIGGER eliminar_articulo_al_borrar_sub_categoria
BEFORE DELETE ON SUBCATEGORIA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDSUBCATEGORIA = OLD.IDSUBCATEGORIA;
END;

CREATE TRIGGER eliminar_referencias_de_articulo_al_borrarlo
BEFORE DELETE ON ARTICULO
FOR EACH ROW
BEGIN
    DELETE FROM DETALLEEXISTENCIA
    WHERE IDARTICULO = OLD.IDARTICULO;

    DELETE FROM DETALLECOMPRA
    WHERE IDARTICULO = OLD.IDARTICULO;

    DELETE FROM DETALLEVENTA
    WHERE IDARTICULO = OLD.IDARTICULO;

END;

--FACTURAVENTA, CLIENTE
CREATE TRIGGER eliminar_facturas_venta_al_borrar_cliente
BEFORE DELETE ON CLIENTE
FOR EACH ROW
BEGIN
    DELETE FROM FACTURAVENTA
    WHERE IDCLIENTE = OLD.IDCLIENTE;
END;
--FIN

-- TADEO THINGS
CREATE TRIGGER elminar_sucursal_farmacia_al_borrar_direccion
BEFORE DELETE ON DIRECCION
FOR EACH ROW
BEGIN
    DELETE FROM SUCURSALFARMACIA
    WHERE IDDIRECCION = OLD.IDDIRECCION;
END;

CREATE TRIGGER eliminar_detalle_existencia_al_borrar_sucursal_farmacia
BEFORE DELETE ON SUCURSALFARMACIA
BEGIN
    DELETE FROM DETALLEEXISTENCIA
    WHERE IDFARMACIA = OLD.IDFARMACIA;
    DELETE FROM FACTURACOMPRA
    WHERE IDFARMACIA = OLD.IDFARMACIA;
    DELETE FROM FACTURAVENTA
    WHERE IDFARMACIA = OLD.IDFARMACIA;
END;

CREATE TRIGGER trigger_restar_existencia_despues_insert_venta
AFTER INSERT ON DETALLEVENTA
BEGIN
  UPDATE DETALLEEXISTENCIA
  SET CANTIDADEXISTENCIA = CANTIDADEXISTENCIA - NEW.CANTIDADVENTA
  WHERE IDARTICULO = NEW.IDARTICULO
    AND IDFARMACIA = (
      SELECT IDFARMACIA
      FROM FACTURAVENTA
      WHERE IDCLIENTE = NEW.IDCLIENTE
        AND IDVENTA = NEW.IDVENTA
    );
END;

-- FIN TADEO THINGS